blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature request & â“ Questions
    url: https://github.com/near/near-sdk-js/discussions
    about: Use GitHub discussions for feature requests and questions.
