name: Examples
on: 
  pull_request:
  push:
jobs:
  examples:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn && cd examples && yarn
      - name: clean-state
        run: cd examples && yarn build:clean-state && yarn test:clean-state
      - name: counter
        run: cd examples && yarn build:counter && yarn test:counter
      - name: counter-lowlevel
        run: cd examples && yarn build:counter-lowlevel && yarn test:counter-lowlevel
      - name: counter-ts
        run: cd examples && yarn build:counter-ts && yarn test:counter-ts
      - name: cross-contract-call
        run: cd examples && yarn build:cross-contract-call && yarn test:cross-contract-call
      - name: fungible-token-lockable
        run: cd examples && yarn build:fungible-token-lockable && yarn test:fungible-token-lockable
      - name: fungible-token
        run: cd examples && yarn build:fungible-token && yarn test:fungible-token
      - name: non-fungible-token
        run: cd examples && yarn build:non-fungible-token && yarn test:non-fungible-token
      - name: status-message-collections
        run: cd examples && yarn build:status-message-collections && yarn test:status-message-collections
      - name: status-message
        run: cd examples && yarn build:status-message && yarn test:status-message
      - name: parking-lot
        run: cd examples && yarn build:parking-lot && yarn test:parking-lot